name: CI
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: laughedelic/coursier-setup@v1
      with:
        jvm: openjdk:11
    - name: Coursier cache
      uses: coursier/cache-action@v5
    - name: Cache sbt
      uses: actions/cache@v1
      with:
        path: $HOME/.sbt
        key: ${{ runner.os }}-sbt-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
#    - name: Setup Scala
#      uses: olafurpg/setup-scala@v10
#      with:
#        java-version: openjdk@1.11
    - name: Build and Test
      run: |
        sbt mimaReportBinaryIssues test compileDocumentation
        rm -rf "$HOME/.ivy2/local" || true
        find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                       -name "*-LM-SNAPSHOT*"       -delete || true
        find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
        find $HOME/.sbt                              -name "*.lock"               -delete || true